import re
import tomllib
from dataclasses import dataclass
from pathlib import Path
from security_scan import repo

_UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
_UUID_RX = re.compile(_UUID)
# A UUID "referenced as a BWS secret" = a UUID on a line mentioning bws / a secret-id var.
_BWS_LINE_RX = re.compile(r"(?i)(bws\s+secret|fetch_bws_secret|BWS_\w*SECRET_ID|BWS_ACCESS)")

MANIFEST = ".bws-secrets.toml"


def _is_doc(rel: str) -> bool:
    """Documentation, not runtime code. A UUID mentioned only in prose (a plan,
    a README, a break-glass doc) is not a secret the repo *consumes* — so it must
    not drive the manifest. Note: the token-LEAK rules deliberately still scan
    these files; an exposed secret value in a README is a real leak."""
    return rel.endswith(".md") or rel.startswith("docs/") or "/docs/" in rel


def referenced_uuids(repo_path) -> set[str]:
    repo_path = Path(repo_path)
    found: set[str] = set()
    for rel in repo.tracked_files(repo_path):
        if rel == MANIFEST or _is_doc(rel):
            continue
        try:
            text = (repo_path / rel).read_text(errors="ignore")
        except OSError:
            continue
        for line in text.splitlines():
            if _BWS_LINE_RX.search(line):
                found.update(_UUID_RX.findall(line))
    return found


def declared_uuids(repo_path) -> set[str]:
    p = Path(repo_path) / MANIFEST
    if not p.exists():
        return set()
    data = tomllib.loads(p.read_text())
    return {s["uuid"] for s in data.get("secret", []) if "uuid" in s}


@dataclass
class ManifestDiff:
    manifest_exists: bool
    undeclared: set[str]   # referenced in code, not in manifest
    stale: set[str]        # in manifest, not referenced


def diff(repo_path) -> ManifestDiff:
    refd = referenced_uuids(repo_path)
    decl = declared_uuids(repo_path)
    exists = (Path(repo_path) / MANIFEST).exists()
    return ManifestDiff(manifest_exists=exists,
                        undeclared=refd - decl,
                        stale=decl - refd)


def _toml_str(s: str) -> str:
    """Minimal TOML basic-string escaping (backslash and double-quote)."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_manifest(referenced: set[str], enrich: dict[str, dict] | None = None) -> str:
    """Render a .bws-secrets.toml declaring the given secret UUIDs, sorted for
    stable diffs. `enrich` optionally maps uuid -> {"name":..., "project":...}
    to add human-readable context; un-enriched UUIDs are still emitted (with a
    flag comment) so a referenced secret is never silently dropped."""
    enrich = enrich or {}
    lines = [
        "# Secrets this repo consumes, by stable BWS UUID.",
        "# Generated by `security-scan generate-manifest` from runtime code references.",
        "",
    ]
    for uuid in sorted(referenced):
        info = enrich.get(uuid, {})
        lines.append("[[secret]]")
        lines.append(f"uuid = {_toml_str(uuid)}")
        if info.get("name"):
            lines.append(f"name = {_toml_str(info['name'])}")
        else:
            lines.append("# name: not found in BWS — verify this UUID is correct")
        if info.get("project"):
            lines.append(f"project = {_toml_str(info['project'])}")
        lines.append("")
    return "\n".join(lines)
